name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Azure Pipeline
    runs-on: ubuntu-latest  # Oder eine andere gewünschte Plattform
    steps:
      - name: Azure Pipeline Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/fahimehasjadi/Agile-Projekt
          azure-pipeline-name: 'webapp-N'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN}}
